# Generated by Django 3.1 on 2020-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='week',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday')], default='Su', max_length=50, verbose_name='week'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3, verbose_name='month'),
        ),
    ]
