# Generated by Django 3.1 on 2020-10-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201004_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'no rating'), (1, 'low'), (2, 'midle'), (3, 'high')], null=True, verbose_name='rating'),
        ),
    ]
